### ISSUE TITLE
Correction of C++ Standard Flag from '17' to '1z' for clang 4.0 - Linux Job  in  azure-pipelines.yml

### ISSUE THREAD

**Issue by gopi487krishna** [BoostGSoC19/astronomy#122]
Currently the code in boost.Astronomy does not compile successfully on clang 4.0 due to the wrong value of **CXXSTD** flag  being passed to the compiler. Kindly change the value from **17** to **1z** for the compilation to be successful on **clang 4.0**

Current value: azure-pipelines.yml
```
 Clang 4:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,17
          CXX: clang++-4.0
          PACKAGES: clang-4.0
          LLVM_REPO: llvm-toolchain-xenial-4.0
```
Correct value : azure-pipelines.yml
```
 Clang 4:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,1z
          CXX: clang++-4.0
          PACKAGES: clang-4.0
          LLVM_REPO: llvm-toolchain-xenial-4.0
```

**Comment by rjnrohit** [comment]
Also, configuration for test Mac os needs to be updated. These checks are getting cancelled automatically.
