### ISSUE TITLE
Wrong units generated with Cross product

### ISSUE THREAD

**Issue by lpranam** [BoostGSoC19/astronomy#79]
When `cartesian_representation` is crossed with other types of representation wrong units are generated due to resultant units are generated from original units in the return statement.

**Comment by sarthak2007** [comment]
This example explains the error more clearly:
```
auto point1 = make_cartesian_representation(1.0 * meters, 2.0 * meters, 3.0 * meters);
auto point2 = make_spherical_representation(45.0 * bud::degrees, 45.0 * bud::degrees, 1.0 * meters);

auto cross_result = cross(point1, point2);
```

Ideally, it should give `cross_result` with meter^2 as unit of each coordinate. But instead it produces compilation error:
```
error: static assertion failed: All components must have same dimensions
```

**Comment by Zyro9922** [comment]
> This example explains the error more clearly:
> 
> ```
> auto point1 = make_cartesian_representation(1.0 * meters, 2.0 * meters, 3.0 * meters);
> auto point2 = make_spherical_representation(45.0 * bud::degrees, 45.0 * bud::degrees, 1.0 * meters);
> 
> auto cross_result = cross(point1, point2);
> ```
> 
> Ideally, it should give `cross_result` with meter^2 as unit of each coordinate. But instead it produces compilation error:
> 
> ```
> error: static assertion failed: All components must have same dimensions
> ```

Cross product of two vectors is a vector only. 

Cross product between a=(3,−3,1) and b=(4,9,2)
![Screenshot 2019-11-26 at 9 09 52 PM](https://user-images.githubusercontent.com/29565914/69648329-19f4d700-1091-11ea-8e90-40b7374415b4.png)
So the unit will be meter only.

**Comment by Zyro9922** [comment]
> This example explains the error more clearly:
> 
> ```
> auto point1 = make_cartesian_representation(1.0 * meters, 2.0 * meters, 3.0 * meters);
> auto point2 = make_spherical_representation(45.0 * bud::degrees, 45.0 * bud::degrees, 1.0 * meters);
> 
> auto cross_result = cross(point1, point2);
> ```
> 
> Ideally, it should give `cross_result` with meter^2 as unit of each coordinate. But instead it produces compilation error:
> 
> ```
> error: static assertion failed: All components must have same dimensions
> ```

Cross product of two vectors is another vector. Why will the unit be meter^2?

**Comment by lpranam** [comment]
> > This example explains the error more clearly:
> > ```
> > auto point1 = make_cartesian_representation(1.0 * meters, 2.0 * meters, 3.0 * meters);
> > auto point2 = make_spherical_representation(45.0 * bud::degrees, 45.0 * bud::degrees, 1.0 * meters);
> > 
> > auto cross_result = cross(point1, point2);
> > ```
> > 
> > 
> > Ideally, it should give `cross_result` with meter^2 as unit of each coordinate. But instead it produces compilation error:
> > ```
> > error: static assertion failed: All components must have same dimensions
> > ```
> 
> Cross product of two vectors is another vector. Why will the unit be meter^2?

Because the cross product of two vectors is another vector whose length denotes the area of the parallelogram created by the original vectors and this vector will be perpendicular to that area.

Another way to think of it: when you do a cross product of two vectors you will have to multiply one component from each vector with some units and multiplying those components will produce a new unit. i.e if both the vectors and each component are in meter then the resultant component will be in meter^2.

**Comment by Zyro9922** [comment]
So currently `cross` returns magnitude of cross product of two vectors. A constant like 50 meter^2. Then how does it matter if we take the cross with any other cartesian representation like spherical because we will convert that spherical representation to cartesian then take the cross. 

What are we expecting when we take the cross of a spherical and cartesian representation (spherical as the first argument)?

Instead if `cross` returned a vector like a structure of 3 components of the representation like (x,y,z) or (theta, azimuthal angle, distance from the origin) we could easily calculate magnitude from that.
